version: "3"
services:
  node-service:
    container_name: node-service
    build: .
    restart: always
    ports:
      - 8080:8080
    volumes:
      - .:/usr/src/app
      - ./wait-for-it.sh:/usr/src/app/wait-for-it.sh
    depends_on:
      - db
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
      - DB_PORT=${DB_PORT}
    command: ["/usr/src/app/wait-for-it.sh", "backend-db-1:3306", "--", "npm", "run", "dev"]
  db:
    image: mysql:8.0
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306
volumes:
  db-data: