name: Node.js CD

on:
  push:
    branches: [develop, main]
  pull_request:
      types:
        - closed
      branches: [develop, main]
  workflow_run:
    workflows: ["Node.js CI"]
    types:
      - completed

jobs:
  cd:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Setting .env
        run: |
          echo "${{ secrets.ENV }}" >> .env
      - name: Build and Push docker images
        run: |
          docker-compose -f docker-compose.yml build
          docker images
          docker-compose -f docker-compose.yml push
      - name: Execute remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ubuntu/backend
            git stash
            git pull
            docker-compose -f docker-compose.yml down
            docker-compose -f docker-compose.yml pull
            docker-compose -f docker-compose.yml up -d